allowBuilds:
  core-js: false
  core-js-pure: false
  re2: false
  unrs-resolver: false

minimumReleaseAgeExclude:
  - '@types/semver@7.8.0'
  - globals@17.9.0
  - '@es-joy/jsdoc-eslint-parser@0.28.0'
  - '@es-joy/jsdoccomment@0.93.0 || 0.93.1'
  - '@types/node@26.2.0'
  - comment-parser@1.4.8
  - eslint@10.8.1

overrides:
  yargs@^17: 17.7.3

shellEmulator: true
