var NodeType = {
  // NAME: 0,
  // MEMBER: 1,
  // UNION: 2,
  // VARIADIC: 3,
  // RECORD: 4,
  // RECORD_ENTRY: 5,
  // GENERIC: 6,
  // MODULE: 7,
  // OPTIONAL: 8,
  // NULLABLE: 9,
  // NOT_NULLABLE: 10,
  // FUNCTION: 11,
  // ANY: 12,
  // UNKNOWN: 13,

  NAME: 'NAME',
  MEMBER: 'MEMBER',
  UNION: 'UNION',
  VARIADIC: 'VARIADIC',
  RECORD: 'RECORD',
  RECORD_ENTRY: 'RECORD_ENTRY',
  GENERIC: 'GENERIC',
  MODULE: 'MODULE',
  OPTIONAL: 'OPTIONAL',
  NULLABLE: 'NULLABLE',
  NOT_NULLABLE: 'NOT_NULLABLE',
  FUNCTION: 'FUNCTION',
  ANY: 'ANY',
  UNKNOWN: 'UNKNOWN',
};


module.exports = NodeType;
